import { SharedOriginGuard } from '@synapse/shared-types';
import { Card, CardContent, Button } from '@synapse/ui-kit';
import { Routes, Route, Link } from 'react-router-dom';

function Dashboard() {
  return (
    <Card variant="elevated" className="bg-white">
      <CardContent className="p-8">
        <h1 className="text-3xl font-bold text-primary-900 mb-4">Hello from external-mfe!</h1>
        <p className="text-neutral-600 mb-6">
          This Micro Frontend was auto-generated by the internal platform generator.
        </p>
        <div className="bg-primary-50 p-4 rounded-lg border border-primary-100 flex items-center justify-between mb-6">
          <span className="text-sm font-medium text-primary-800">Status</span>
          <span className="px-3 py-1 bg-success/10 text-success text-xs font-bold rounded-full">
            Federated & Ready
          </span>
        </div>
        <Link to="detail">
          <Button variant="default">Test Nested Routing</Button>
        </Link>
      </CardContent>
    </Card>
  );
}

function Detail() {
  return (
    <Card variant="elevated" className="bg-white">
      <CardContent className="p-8">
        <h1 className="text-2xl font-bold text-neutral-900 mb-2">Detail Page</h1>
        <p className="text-neutral-600 mb-6">
          This page proves that sub-routing inside the MFE works independently of the Shell!
        </p>
        <Link to="..">
          <Button variant="outline">← Back to Dashboard</Button>
        </Link>
      </CardContent>
    </Card>
  );
}

export function App() {
  return (
    <SharedOriginGuard>
      <div className="p-8">
        {/*
          MFE Routing Best Practice: 
          Always use <Routes> for internal navigation. Do NOT wrap this in <BrowserRouter>. 
          The Shell takes care of the <BrowserRouter>.
        */}
        <Routes>
          <Route index element={<Dashboard />} />
          <Route path="detail" element={<Detail />} />
        </Routes>
      </div>
    </SharedOriginGuard>
  );
}

export default App;
